/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        /* All tokens now reference CSS variables so dark mode works automatically */
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-primary-fixed':          '#0f0069',
        'on-error-container':        'var(--color-on-error-container)',
        'on-secondary-fixed-variant':'#3f465c',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-tertiary-fixed':         '#07006c',
        'on-tertiary':               'var(--color-on-tertiary)',
        'primary-container':         'var(--color-primary-container)',
        'on-secondary':              'var(--color-on-secondary)',
        'primary-fixed':             '#e2dfff',
        'inverse-surface':           'var(--color-inverse-surface)',
        'on-primary-container':      'var(--color-on-primary-container)',
        'on-secondary-container':    'var(--color-on-secondary-container)',
        'tertiary-container':        'var(--color-tertiary-container)',
        'surface-container-lowest':  'var(--color-surface-container-lowest)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'on-error':                  'var(--color-on-error)',
        outline:                     'var(--color-outline)',
        'on-primary-fixed-variant':  '#3323cc',
        'outline-variant':           'var(--color-outline-variant)',
        background:                  'var(--color-background)',
        'on-surface':                'var(--color-on-surface)',
        'surface-bright':            'var(--color-surface-bright)',
        'surface-dim':               'var(--color-surface-dim)',
        'primary-fixed-dim':         '#c3c0ff',
        'tertiary-fixed-dim':        '#c0c1ff',
        secondary:                   'var(--color-secondary)',
        'secondary-container':       'var(--color-secondary-container)',
        error:                       'var(--color-error)',
        'inverse-primary':           'var(--color-inverse-primary)',
        'secondary-fixed':           '#dae2fd',
        'secondary-fixed-dim':       '#bec6e0',
        tertiary:                    'var(--color-tertiary)',
        'tertiary-fixed':            '#e1e0ff',
        'surface-container':         'var(--color-surface-container)',
        surface:                     'var(--color-surface)',
        'error-container':           'var(--color-error-container)',
        'surface-tint':              'var(--color-surface-tint)',
        'on-surface-variant':        'var(--color-on-surface-variant)',
        'on-tertiary-container':     'var(--color-on-tertiary-container)',
        primary:                     'var(--color-primary)',
        'on-secondary-fixed':        '#131b2e',
        'inverse-on-surface':        'var(--color-inverse-on-surface)',
        'on-primary':                'var(--color-on-primary)',
        'surface-variant':           'var(--color-surface-variant)',
        'surface-container-low':     'var(--color-surface-container-low)',
        'on-background':             'var(--color-on-background)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.375rem',
        md: '0.625rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        gutter: '20px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        'geist-mono': ['Geist Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'mono-label': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 2px 12px -2px rgba(0,0,0,0.08), 0 1px 3px -1px rgba(0,0,0,0.06)',
        'card-lg': '0 8px 24px -4px rgba(0,0,0,0.12), 0 2px 8px -2px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}
