/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#2f2ebe',
        'on-primary-fixed': '#0f0069',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-secondary': '#ffffff',
        'primary-fixed': '#e2dfff',
        'inverse-surface': '#213145',
        'on-primary-container': '#dad7ff',
        'on-secondary-container': '#5c647a',
        'tertiary-container': '#4b4dd8',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dce9ff',
        'on-error': '#ffffff',
        outline: '#777587',
        'on-primary-fixed-variant': '#3323cc',
        'outline-variant': '#c7c4d8',
        background: '#f8f9ff',
        'on-surface': '#0b1c30',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'primary-fixed-dim': '#c3c0ff',
        'tertiary-fixed-dim': '#c0c1ff',
        secondary: '#565e74',
        'secondary-container': '#dae2fd',
        error: '#ba1a1a',
        'inverse-primary': '#c3c0ff',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        tertiary: '#3130c0',
        'tertiary-fixed': '#e1e0ff',
        'surface-container': '#e5eeff',
        surface: '#f8f9ff',
        'error-container': '#ffdad6',
        'surface-tint': '#4d44e3',
        'on-surface-variant': '#464555',
        'on-tertiary-container': '#d9d8ff',
        primary: '#3525cd',
        'on-secondary-fixed': '#131b2e',
        'inverse-on-surface': '#eaf1ff',
        'on-primary': '#ffffff',
        'surface-variant': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        'on-background': '#0b1c30',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        gutter: '20px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        'geist-mono': ['Geist Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'mono-label': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
