# ===============================
# DATASOURCE - MySQL (desativado)
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/smartpdv?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# DATASOURCE - Oracle (ativo)
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=smartpdv123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000



# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto MySQL (desativado)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Dialeto Oracle (ativo)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ===============================
# PERFORMANCE
# ===============================
spring.jpa.open-in-view=false
